### ISSUE TITLE
error in forward_cuda_kernel: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zhenxing9968** [sczhou/STFAN#16]
Environment:
```
  Ubuntu 18.04
  python 3.7
  gcc 7.5.0
  pytorch 1.11.0
  CUDA 11.3
  Device: 3090
```
Build FAC layer sucess. 
My code:
```
import os
import torch
import numpy as np
from models import DeblurNet

c_net = DeblurNet.DeblurNet()
c_net.to(torch.device("cuda"))

img_blur = torch.randn((1, 3, 256, 256)).cuda()
last_img_blur = torch.randn((1, 3, 256, 256)).cuda()
output_last_img = torch.randn((1, 3, 256, 256)).cuda()

aa = c_net.forward(img_blur, last_img_blur, output_last_img, None)
print(aa.shape)
```
ERROR info:
```
error in forward_cuda_kernel: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "temp.py", line 15, in <module>
    aa = c_net.forward(img_blur, last_img_blur, output_last_img, output_last_fea)
  File "/home/users/zxzhao/projects/STFAN/models/DeblurNet.py", line 109, in forward
    conv3_d_k = self.kconv_deblur(conv3_d, kernel_deblur)
  File "/home/users/zxzhao/app/anaconda3/envs/LEDVDI_3090/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/users/zxzhao/projects/STFAN/models/FAC/kernelconv2d/KernelConv2D.py", line 87, in forward
    return KernelConv2DFunction.apply(input_pad, kernel, self.kernel_size)
  File "/home/users/zxzhao/projects/STFAN/models/FAC/kernelconv2d/KernelConv2D.py", line 37, in forward
    kernelconv2d_cuda.forward(input, kernel, intKernelSize, output)
RuntimeError: CUDA call failed

```
But running this code on other machines（Device: 1660s,   CUDA 10.2, pytorch 1.11.0） is normal, could you help me?

**Comment by buwangchuxin1992** [comment]
> Environment:
> 
> ```
>   Ubuntu 18.04
>   python 3.7
>   gcc 7.5.0
>   pytorch 1.11.0
>   CUDA 11.3
>   Device: 3090
> ```
> 
> Build FAC layer sucess. My code:
> 
> ```
> import os
> import torch
> import numpy as np
> from models import DeblurNet
> 
> c_net = DeblurNet.DeblurNet()
> c_net.to(torch.device("cuda"))
> 
> img_blur = torch.randn((1, 3, 256, 256)).cuda()
> last_img_blur = torch.randn((1, 3, 256, 256)).cuda()
> output_last_img = torch.randn((1, 3, 256, 256)).cuda()
> 
> aa = c_net.forward(img_blur, last_img_blur, output_last_img, None)
> print(aa.shape)
> ```
> 
> ERROR info:
> 
> ```
> error in forward_cuda_kernel: no kernel image is available for execution on the device
> Traceback (most recent call last):
>   File "temp.py", line 15, in <module>
>     aa = c_net.forward(img_blur, last_img_blur, output_last_img, output_last_fea)
>   File "/home/users/zxzhao/projects/STFAN/models/DeblurNet.py", line 109, in forward
>     conv3_d_k = self.kconv_deblur(conv3_d, kernel_deblur)
>   File "/home/users/zxzhao/app/anaconda3/envs/LEDVDI_3090/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/users/zxzhao/projects/STFAN/models/FAC/kernelconv2d/KernelConv2D.py", line 87, in forward
>     return KernelConv2DFunction.apply(input_pad, kernel, self.kernel_size)
>   File "/home/users/zxzhao/projects/STFAN/models/FAC/kernelconv2d/KernelConv2D.py", line 37, in forward
>     kernelconv2d_cuda.forward(input, kernel, intKernelSize, output)
> RuntimeError: CUDA call failed
> ```
> 
> But running this code on other machines（Device: 1660s, CUDA 10.2, pytorch 1.11.0） is normal, could you help me?

have you solves this problem now?I have same problem when use 3090 on cuda11,thanks

**Comment by yuanlinwang** [comment]
@buwangchuxin1992 hello,
i add 
`'-gencode', 'arch=compute_80,code=sm_80',
    '-gencode', 'arch=compute_86,code=sm_86',
    '-gencode', 'arch=compute_86,code=compute_86'`
behind nvcc_args, then install.sh 
it can support the cuda 11.0+
