### ISSUE TITLE
cannot import kernelConv2d_cuda

### ISSUE THREAD

**Issue by NTGN** [sczhou/STFAN#5]
I want to test the pictures with the weights you provided. After configuring the environment and compiling, I encountered a problem. In the eighth line of KernelConv2D.py, I cannot import kernelConv2d_cuda. I cannot find the file kernelConv2d_cuda.py in the project. Can you provide me some guidance?

**Comment by sczhou** [comment]
you may check your experiments if it can require our recommended prerequisites first.
https://github.com/sczhou/STFAN#prerequisites
Note that it has strict requirements for the gcc and PyTorch version.

**Comment by karentwan** [comment]
I installed Pytorch 1.0.1, 0.4 and 1.4, all showing "cannot import kernelConv2d_cuda". Could you tell me which pytorch version you used
