### ISSUE TITLE
RuntimeError: function KernelConv2DFunctionBackward,bug in KernelConv2D.py

### ISSUE THREAD

**Issue by huicongzhang** [sczhou/STFAN#8]
In `class KernelConv2DFunction` ,The number of return Variable arguments of backward() funtion is not equal to the number of input  Variable arguments of forward() function.Maybe backward() funtion should change `return grad_input, grad_kernel` to `return grad_input, grad_kernel,None`.that's can fix it

**Comment by sczhou** [comment]
You are right. I forgot to change backward() output when I transformed it into the static method. Thanks for your kind notice.
